const questionsData = [
  {
    question: "What is the capital of France?",
    options: ["Paris", "London", "Berlin", "Madrid"],
    correctAnswer: "Paris",
    flag: "https://flagcdn.com/w320/fr.png",
  },
  {
    question: "What is the capital of Italy?",
    options: ["Rome", "Paris", "Berlin", "Lisbon"],
    correctAnswer: "Rome",
    flag: "https://flagcdn.com/w320/it.png",
  },
  {
    question: "What is the capital of Japan?",
    options: ["Tokyo", "Beijing", "Seoul", "Bangkok"],
    correctAnswer: "Tokyo",
    flag: "https://flagcdn.com/w320/jp.png",
  },
  {
    question: "What is the capital of Australia?",
    options: ["Canberra", "Sydney", "Melbourne", "Brisbane"],
    correctAnswer: "Canberra",
    flag: "https://flagcdn.com/w320/au.png",
  },
  {
    question: "What is the capital of Canada?",
    options: ["Ottawa", "Toronto", "Vancouver", "Montreal"],
    correctAnswer: "Ottawa",
    flag: "https://flagcdn.com/w320/ca.png",
  },
  {
    question: "What is the capital of Brazil?",
    options: ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador"],
    correctAnswer: "Brasília",
    flag: "https://flagcdn.com/w320/br.png",
  },
  {
    question: "What is the capital of Germany?",
    options: ["Berlin", "Munich", "Frankfurt", "Hamburg"],
    correctAnswer: "Berlin",
    flag: "https://flagcdn.com/w320/de.png",
  },
  {
    question: "What is the capital of Russia?",
    options: ["Moscow", "Saint Petersburg", "Kazan", "Sochi"],
    correctAnswer: "Moscow",
    flag: "https://flagcdn.com/w320/ru.png",
  },
  {
    question: "What is the capital of China?",
    options: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen"],
    correctAnswer: "Beijing",
    flag: "https://flagcdn.com/w320/cn.png",
  },
  {
    question: "What is the capital of India?",
    options: ["New Delhi", "Mumbai", "Kolkata", "Bangalore"],
    correctAnswer: "New Delhi",
    flag: "https://flagcdn.com/w320/in.png",
  },
  {
    question: "What is the capital of the United Kingdom?",
    options: ["London", "Edinburgh", "Manchester", "Birmingham"],
    correctAnswer: "London",
    flag: "https://flagcdn.com/w320/gb.png",
  },
  {
    question: "What is the capital of South Korea?",
    options: ["Seoul", "Busan", "Incheon", "Daegu"],
    correctAnswer: "Seoul",
    flag: "https://flagcdn.com/w320/kr.png",
  },
  {
    question: "What is the capital of Egypt?",
    options: ["Cairo", "Alexandria", "Giza", "Luxor"],
    correctAnswer: "Cairo",
    flag: "https://flagcdn.com/w320/eg.png",
  },
  {
    question: "What is the capital of South Africa?",
    options: ["Pretoria", "Johannesburg", "Cape Town", "Durban"],
    correctAnswer: "Pretoria",
    flag: "https://flagcdn.com/w320/za.png",
  },
  {
    question: "What is the capital of Argentina?",
    options: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"],
    correctAnswer: "Buenos Aires",
    flag: "https://flagcdn.com/w320/ar.png",
  },
  {
    question: "What is the capital of Mexico?",
    options: ["Mexico City", "Guadalajara", "Monterrey", "Cancún"],
    correctAnswer: "Mexico City",
    flag: "https://flagcdn.com/w320/mx.png",
  },
  {
    question: "What is the capital of Turkey?",
    options: ["Ankara", "Istanbul", "Izmir", "Antalya"],
    correctAnswer: "Ankara",
    flag: "https://flagcdn.com/w320/tr.png",
  },
  {
    question: "What is the capital of Saudi Arabia?",
    options: ["Riyadh", "Jeddah", "Mecca", "Medina"],
    correctAnswer: "Riyadh",
    flag: "https://flagcdn.com/w320/sa.png",
  },
  {
    question: "What is the capital of Nigeria?",
    options: ["Abuja", "Lagos", "Kano", "Ibadan"],
    correctAnswer: "Abuja",
    flag: "https://flagcdn.com/w320/ng.png",
  },
  {
    question: "What is the capital of Spain?",
    options: ["Madrid", "Barcelona", "Valencia", "Seville"],
    correctAnswer: "Madrid",
    flag: "https://flagcdn.com/w320/es.png",
  },
  {
    question: "What is the capital of Portugal?",
    options: ["Lisbon", "Porto", "Braga", "Coimbra"],
    correctAnswer: "Lisbon",
    flag: "https://flagcdn.com/w320/pt.png",
  },
  {
    question: "What is the capital of Greece?",
    options: ["Athens", "Thessaloniki", "Patras", "Heraklion"],
    correctAnswer: "Athens",
    flag: "https://flagcdn.com/w320/gr.png",
  },
  {
    question: "What is the capital of Kenya?",
    options: ["Nairobi", "Mombasa", "Kisumu", "Eldoret"],
    correctAnswer: "Nairobi",
    flag: "https://flagcdn.com/w320/ke.png",
  },

  {
    question: "What is the capital of Thailand?",
    options: ["Bangkok", "Chiang Mai", "Pattaya", "Phuket"],
    correctAnswer: "Bangkok",
    flag: "https://flagcdn.com/w320/th.png",
  },
  {
    question: "What is the capital of Indonesia?",
    options: ["Jakarta", "Surabaya", "Bandung", "Medan"],
    correctAnswer: "Jakarta",
    flag: "https://flagcdn.com/w320/id.png",
  },
  {
    question: "What is the capital of Pakistan?",
    options: ["Islamabad", "Karachi", "Lahore", "Rawalpindi"],
    correctAnswer: "Islamabad",
    flag: "https://flagcdn.com/w320/pk.png",
  },
  {
    question: "What is the capital of Malaysia?",
    options: ["Kuala Lumpur", "George Town", "Johor Bahru", "Malacca"],
    correctAnswer: "Kuala Lumpur",
    flag: "https://flagcdn.com/w320/my.png",
  },
  {
    question: "What is the capital of Bangladesh?",
    options: ["Dhaka", "Chittagong", "Khulna", "Rajshahi"],
    correctAnswer: "Dhaka",
    flag: "https://flagcdn.com/w320/bd.png",
  },
  {
    question: "What is the capital of Vietnam?",
    options: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hue"],
    correctAnswer: "Hanoi",
    flag: "https://flagcdn.com/w320/vn.png",
  },
  {
    question: "What is the capital of the Philippines?",
    options: ["Manila", "Cebu City", "Davao City", "Quezon City"],
    correctAnswer: "Manila",
    flag: "https://flagcdn.com/w320/ph.png",
  },
  {
    question: "What is the capital of Sweden?",
    options: ["Stockholm", "Gothenburg", "Malmö", "Uppsala"],
    correctAnswer: "Stockholm",
    flag: "https://flagcdn.com/w320/se.png",
  },
  {
    question: "What is the capital of Norway?",
    options: ["Oslo", "Bergen", "Stavanger", "Trondheim"],
    correctAnswer: "Oslo",

    flag: "https://flagcdn.com/w320/no.png",
  },
  {
    question: "What is the capital of Finland?",
    options: ["Helsinki", "Tampere", "Turku", "Oulu"],
    correctAnswer: "Helsinki",
    flag: "https://flagcdn.com/w320/fi.png",
  },
  {
    question: "What is the capital of Denmark?",
    options: ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
    correctAnswer: "Copenhagen",
    flag: "https://flagcdn.com/w320/dk.png",
  },
  {
    question: "What is the capital of Iceland?",
    options: ["Reykjavik", "Akureyri", "Hafnarfjörður", "Keflavík"],
    correctAnswer: "Reykjavik",
    flag: "https://flagcdn.com/w320/is.png",
  },
  {
    question: "What is the capital of Poland?",
    options: ["Warsaw", "Krakow", "Wrocław", "Poznań"],
    correctAnswer: "Warsaw",
    flag: "https://flagcdn.com/w320/pl.png",
  },
  {
    question: "What is the capital of the Netherlands?",
    options: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"],
    correctAnswer: "Amsterdam",
    flag: "https://flagcdn.com/w320/nl.png",
  },
  {
    question: "What is the capital of Belgium?",
    options: ["Brussels", "Antwerp", "Ghent", "Bruges"],
    correctAnswer: "Brussels",
    flag: "https://flagcdn.com/w320/be.png",
  },
  {
    question: "What is the capital of Austria?",
    options: ["Vienna", "Salzburg", "Graz", "Innsbruck"],
    correctAnswer: "Vienna",
    flag: "https://flagcdn.com/w320/at.png",
  },
  {
    question: "What is the capital of Switzerland?",
    options: ["Bern", "Zurich", "Geneva", "Basel"],
    correctAnswer: "Bern",
    flag: "https://flagcdn.com/w320/ch.png",
  },
  {
    question: "What is the capital of Hungary?",
    options: ["Budapest", "Debrecen", "Szeged", "Pécs"],
    correctAnswer: "Budapest",
    flag: "https://flagcdn.com/w320/hu.png",
  },
  {
    question: "What is the capital of Czech Republic?",
    options: ["Prague", "Brno", "Ostrava", "Plzeň"],
    correctAnswer: "Prague",
    flag: "https://flagcdn.com/w320/cz.png",
  },
  {
    question: "What is the capital of Romania?",
    options: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași"],
    correctAnswer: "Bucharest",
    flag: "https://flagcdn.com/w320/ro.png",
  },
  {
    question: "What is the capital of Bulgaria?",
    options: ["Sofia", "Plovdiv", "Varna", "Burgas"],
    correctAnswer: "Sofia",
    flag: "https://flagcdn.com/w320/bg.png",
  },
  {
    question: "What is the capital of Croatia?",
    options: ["Zagreb", "Split", "Rijeka", "Osijek"],
    correctAnswer: "Zagreb",
    flag: "https://flagcdn.com/w320/hr.png",
  },
  {
    question: "What is the capital of Serbia?",
    options: ["Belgrade", "Novi Sad", "Niš", "Kragujevac"],
    correctAnswer: "Belgrade",
    flag: "https://flagcdn.com/w320/rs.png",
  },
  {
    question: "What is the capital of Slovakia?",
    options: ["Bratislava", "Košice", "Žilina", "Prešov"],
    correctAnswer: "Bratislava",
    flag: "https://flagcdn.com/w320/sk.png",
  },
];

export default questionsData;
